AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  Create S3 buckets and cross-account role for ADX  data plane with minimal
  permissions.

Globals:
  Function:
    Timeout: 300
Parameters:
  AssetBucketName:
    Type: String
    Default: rearc-data-provider
    Description: Bucket containing assets and referenced in the manifest.
  CreateAssetBucket:
    Type: String
    AllowedValues:
      - true
      - false
  RegistrationTopicARN:
    Type: String
    Description: >-
      SNS Topic ARN for registering with the control plane - provided during
      onboarding
  ControlPlaneAccount:
    Type: String
    Description: ID of the control plane account to connect to
    Default: 412981388937
  ExternalId:
    Type: String
    Description: External ID that Rearc will use when accessing resources on this account
    Default: rearcdata
Conditions:
  ShouldCreateAssetBucket: !Equals
    - true
    - !Ref CreateAssetBucket

Resources:
  AssetBucket:
    Type: 'AWS::S3::Bucket'
    Condition: ShouldCreateAssetBucket
    DeletionPolicy: "Retain"
    UpdateReplacePolicy: "Retain"
    Properties: 
      BucketName: !Ref AssetBucketName
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 87ff4070-acae-4e1a-aec1-6ab8df059850
  CrossAccountRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub 
        - 'Rearc-CrossAccountRole-${DataPlaneAccount}'
        - {DataPlaneAccount: !Ref AWS::AccountId }
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${ControlPlaneAccount}:root'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref ExternalId
            Sid: ''
      Path: /
      Policies:
        - PolicyName: DataExchangeActions
          PolicyDocument:
            Statement:
              - Action:
                - dataexchange:GetDataSet
                - dataexchange:ListDataSets
                - dataexchange:UpdateRevision
                - dataexchange:ListJobs
                - dataexchange:GetJob
                - dataexchange:CreateAsset
                - dataexchange:GetRevision
                - dataexchange:CreateJob
                - dataexchange:CreateRevision
                - dataexchange:UpdateDataSet
                - dataexchange:UpdateAsset
                - dataexchange:StartJob
                - dataexchange:ListDataSetRevisions
                Effect: Allow
                Resource: "*"
        - PolicyName: MarketplaceActions
          PolicyDocument:
            Version: '2012-10-17'
            Statement: 
              - Effect: Allow
                Action: 
                  - "aws-marketplace:ListChangeSets"
                  - "aws-marketplace:DescribeChangeSet"
                  - "aws-marketplace:StartChangeSet"
                  - "aws-marketplace:CancelChangeSet"
                  - "aws-marketplace:ListEntities"
                  - "aws-marketplace:DescribeEntity"
                  - "aws-marketplace:ListTasks"
                  - "aws-marketplace:DescribeTask"
                  - "aws-marketplace:UpdateTask"
                  - "aws-marketplace:CompleteTask"
                Resource: '*'
        - PolicyName: S3AssetBucketAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Join ['', ['arn:aws:s3:::',!Ref AssetBucketName, '/*']]
                  - !Join ['', ['arn:aws:s3:::',!Ref AssetBucketName, '*']]
                Condition:
                  ForAnyValue:StringEquals:
                    aws:CalledVia: dataexchange.amazonaws.com
        - PolicyName: S3ADXBucketAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource: arn:aws:s3:::*aws-data-exchange*
                Condition:
                  ForAnyValue:StringEquals:
                    aws:CalledVia: dataexchange.amazonaws.com
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                Resource: arn:aws:s3:::*aws-data-exchange*
                Condition:
                  ForAnyValue:StringEquals:
                    aws:CalledVia: dataexchange.amazonaws.com
  RegistrationCustomResource:
    Properties:
      ServiceToken: !Ref RegistrationTopicARN 
      ControlPlaneRoleArn: !GetAtt CrossAccountRole.Arn 
      ControlPlaneExternalId: !Ref ExternalId
      CustomerID: !Ref AWS::AccountId 
    Type: Custom::RegistrationCustomResource
    Version: '1.0'
