AWSTemplateFormatVersion: 2010-09-09
Transform: 'AWS::Serverless-2016-10-31'
Description: >
  Create S3 buckets and cross-account role for ADX  data plane with minimal
  permissions.

Globals:
  Function:
    Timeout: 300
Parameters:
  AssetBucketName:
    Type: String
    Default: rearc-data-provider
    Description: Bucket containing assets and referenced in the manifest.
  CreateAssetBucket:
    Type: String
    AllowedValues:
      - true
      - false
  ControlPlaneAccount:
    Type: String
    Description: ID of the control plane account to connect to
  ExternalId:
    Type: String
    Description: >-
      External ID for connecting to the control plane - provided during
      onboarding

Conditions:
  ShouldCreateAssetBucket: !Equals
    - true
    - !Ref CreateAssetBucket

Resources:
  AssetBucket:
    Type: 'AWS::S3::Bucket'
    Condition: ShouldCreateAssetBucket
    Properties: 
      BucketName: !Ref AssetBucketName
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 87ff4070-acae-4e1a-aec1-6ab8df059850
  CrossAccountRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: 'sts:AssumeRole'
            Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${ControlPlaneAccount}:root'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref ExternalId
            Sid: ''
      Path: /
      Policies:
        - PolicyName: RearcControlPlaneAccountAccess
          PolicyDocument:
            Statement:
              - Action:
                - dataexchange:GetDataSet
                - dataexchange:ListDataSets
                - dataexchange:UpdateRevision
                - dataexchange:ListJobs
                - dataexchange:GetJob
                - dataexchange:CreateAsset
                - dataexchange:GetRevision
                - dataexchange:CreateJob
                - dataexchange:CreateRevision
                - dataexchange:UpdateDataSet
                - dataexchange:UpdateAsset
                - dataexchange:StartJob
                - dataexchange:ListDataSetRevisions
                Effect: Allow
                Resource: "*"
        - PolicyName: MarketplaceActions
          PolicyDocument:
            Version: '2012-10-17'
            Statement: 
              - Effect: Allow
                Action: 
                  - aws-marketplace:*
                Resource: '*'
        - PolicyName: S3AssetBucketFullAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement: 
              - Effect: Allow
                Action: 
                  - s3:*
                Resource: !Join
                  - ""
                  - - 'arn:aws:s3:::'
                    - !Ref AssetBucketName
                    - '/*'

