name: Validate

on:
  push:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Validate CDK
        run: |
          cd cdk
          npm install
          npm test

      - name: Validate CloudFormation
        run: |
          cd cdk
          npm run synth
          diff <(head -n -8 template.yaml) <(head -n -8 ../cloudformation/adx-data-plane.cfn.yaml)